/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoredsocial;

import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author enigm
 */
public class Menciones extends javax.swing.JFrame {
    private static Tweets t=new Tweets();
    private String[][] menciones; 
    private int[] numeroMenciones; 
    private String usuarioActual; 
    private DefaultListModel<String> mencionesListModel;

    /**
     * Creates new form Menciones
     */
    public Menciones() {
        initComponents();
        this.setLocationRelativeTo(null);
        String[] menciones=Tweets.obtenerMenciones();
        mencionesList.setListData(menciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        scrollPaneMenciones = new javax.swing.JScrollPane();
        mencionesList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        scrollPaneMenciones.setViewportView(mencionesList);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menciones");

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28)
                        .addComponent(scrollPaneMenciones, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneMenciones, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(32, 32, 32))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Timeline TM = new Timeline();
        TM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
/*
    private void inicializarDatos() {
        this.usuarioActual = Users.getUsuariologgeado();  
        
        menciones = new String[Users.usuarios.length][10];
        numeroMenciones = new int[Users.usuarios.length]; 
        
        mencionesListModel = new DefaultListModel<>();
        mencionesList.setModel(mencionesListModel);

        mostrarMenciones();
    }
    
    private void mostrarMenciones() {
    int indiceUsuario = obtenerIndiceUsuario(usuarioActual);

    if (indiceUsuario == -1 || numeroMenciones[indiceUsuario] == 0) {
        mencionesListModel.addElement("No tienes menciones aún");
    } else {
        mencionesListModel.clear();
        for (int i = 0; i < numeroMenciones[indiceUsuario]; i++) {
            mencionesListModel.addElement(menciones[indiceUsuario][i]);
        }
    }
    }
    
    public void publicarTwit(String usuarioQuePublica, String mensaje, Calendar fecha) {
        for (Users u : Users.usuarios) {
            if (u != null && mensaje.contains("@" + u.username)) {
                agregarMencion(u.username, usuarioQuePublica, mensaje, fecha);
            }
        }
    }
    
    public void agregarMencion(String usuarioMencionado, String usuarioQuePublica, String mensaje, Calendar fecha) {
        int indiceUsuario = obtenerIndiceUsuario(usuarioMencionado);
        if (indiceUsuario != -1 && numeroMenciones[indiceUsuario] < menciones[indiceUsuario].length) {
            
            String fechaFormateada = fecha.get(Calendar.DAY_OF_MONTH) + "/" + (fecha.get(Calendar.MONTH) + 1);
            
            String mencion = usuarioQuePublica + ": \"" + mensaje + "\"  (" + fechaFormateada + ")";
            
            menciones[indiceUsuario][numeroMenciones[indiceUsuario]] = mencion;
            
            numeroMenciones[indiceUsuario]++;
            
            if (usuarioMencionado.equals(usuarioActual)) {
                mostrarMenciones();
            }
        }
    }
    
    private int obtenerIndiceUsuario(String usuario) {
        for (int i = 0; i < Users.usuarios.length; i++) {
            if (Users.usuarios[i] != null && Users.usuarios[i].username.equals(usuario)) {
                return i;
            }
        }
        return -1;  
    }
    */
    
    
    

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menciones().setVisible(true);
            }
        });
    }

    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList<String> mencionesList;
    private javax.swing.JScrollPane scrollPaneMenciones;
    // End of variables declaration//GEN-END:variables
}
